northwind:
  outputs:
    dev:
      dbname: "{{ env_var('NORTHWIND_DB_NAME') }}"
      user:   "{{ env_var('NORTHWIND_DB_USER') }}"
      pass:   "{{ env_var('NORTHWIND_DB_PASSWORD') }}"
      host:   "{{ env_var('NORTHWIND_DB_HOST') }}"
      schema: "{{ env_var('NORTHWIND_DB_SCHEMA') }}"
      type:   postgres
      threads: 3
      port: 5432
  target: dev
