
unit_tests:
  - name: v1_test_fact_inventory_full_refresh
    model: fact_inventory
    versions:
      include: 
        - 1
    overrides:
      macros:
        is_incremental: false 
    given:
      - input: ref('stg_inventory', version=1)
        rows:
        - {dbt_scd_id: a, units_in_stock: 10, units_on_order: 20, reorder_level: 20, dbt_updated_at: 2020-01-01 00:00:00}
      
      - input: ref('dim_suppliers')
        rows: []

      - input: ref('dim_products')
        rows: []
    expect:
      rows:
        - {record_id: a, units_in_stock: 10, units_on_order: 20, reorder_level: 20, updated_at: 2020-01-01 00:00:00}


  - name: v1_test_fact_inventory_incremental
    model: fact_inventory
    versions:
      include: 
        - 1
    overrides:
      macros:
        is_incremental: true
    given:
      - input: ref('stg_inventory.v1')
        rows:
          - {dbt_scd_id: b, units_in_stock: 50, units_on_order: 10, reorder_level: 20, dbt_updated_at: 2020-01-02 00:00:00}
      
      - input: ref('dim_suppliers')
        rows: []
      
      - input: ref('dim_products')
        rows: []
        
      - input: this
        rows:
          - {record_id: a, units_in_stock: 10, units_on_order: 20, reorder_level: 20, updated_at: 2020-01-01 00:00:00}
    
    expect:
      # what will be inserted/merged into my_incremental_model
      rows:
        - {record_id: b, units_in_stock: 50, units_on_order: 10, reorder_level: 20, updated_at: 2020-01-02 00:00:00}